transport:
  name: winrm

provisioner:
  name: chef_zero
  #require_chef_omnibus: 11.16.4
  require_chef_omnibus: 12.3.0
  # Obtained from https://www.chef.io/chef/metadata?p=windows&m=x86_64&pv=2012r2&v=12.2.1
  chef_metadata_url: 'file:///c:/share/chef/metadata/windows_v12.3.0.txt'

driver:
  forward_agent: yes
  name: vagrant
  gui: true
  vm_hostname:
  network:
  - ["private_network", {ip: "192.168.56.30"}]
  # Mount local /Users/apop/chef-kits folder as c:\share on the VM  
  synced_folders:
  - ['/Users/apop/chef-kits', 'c:/share', 'disabled: false']
  customize:
    cpus: 2
    memory: 4096

platforms:
  - name: windows2012
    driver_config:
      box: win2012r2-nocm

suites:
  - name: default
    run_list:
      - recipe[mywin-cookbook::default]
      - recipe[mywin-cookbook::sample_dsc]
    attributes:
      mywin-cookbook:
        chef_package: 'file:///c:/share/chef/chef-client-12.3.0-1.msi'
      powershell:
        powershell5:
          url: 'file:///c:/share/windows/WindowsBlue-KB3037315-x64.msu'
          checksum: '9a24de7b85fae96a87188a7fdaab27da3bc90d89426594cdc5f962234a61b7bd'
