Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "win2012r2"
  c.vm.network(:private_network, {:ip=>"192.168.56.30"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/tgondorf/chef-kits", "c:/share", disabled: false
  c.vm.provider :virtualbox do |p|
    p.gui = true
    p.customize ["modifyvm", :id, "--cpus", "2"]
    p.customize ["modifyvm", :id, "--memory", "4096"]
  end
end
